// Fonte: relato fornecido pelo proprietário na conversa de implementação.
// Métricas comparativas não fornecidas. O case do portal também se apoia no repositório.
module.exports = [{
  id: 'case-zadoni-presentes', kind: 'article', caseStudy: true,
  slug: 'cases/zadoni-presentes/', label: 'Case Zadoni Presentes',
  image: 'assets/images/zadoni-presentes-site.jpg',
  imageAlt: 'Página inicial da Zadoni Presentes com apresentação da loja, cesta de presentes e categorias de produtos',
  projectUrl: 'https://zadonipresentes.com.br/',
  imageCaption: 'Página inicial do projeto',
  projectLinkLabel: 'Visitar o site da Zadoni Presentes',
  title: 'Case Zadoni Presentes: site e SEO Local em Canaã | Zadoni Digital',
  description: 'Conheça o trabalho de site, SEO Local e Perfil da Empresa na Zadoni Presentes, negócio próprio de Adonias Joshua em Canaã dos Carajás.',
  h1: 'Zadoni Presentes: estruturação da presença digital em Canaã',
  lead: 'Site, páginas de produtos, SEO técnico e Perfil da Empresa conectados ao atendimento pelo WhatsApp. Um projeto próprio conduzido por Adonias Joshua.',
  sections: [
    ['Contexto e responsabilidade', '<p>A Zadoni Presentes é um negócio de comércio local em Canaã dos Carajás, Pará, pertencente a Adonias Joshua, criador da Zadoni Digital e responsável técnico e estratégico pelo projeto.</p><p>Este case apresenta as ações descritas por Adonias em seu relato sobre o trabalho. A relação de propriedade é parte do contexto: trata-se de um projeto próprio.</p><p><strong>Case em desenvolvimento:</strong> o relato das intervenções já está organizado; a documentação de métricas e períodos de comparação permanece em preparação.</p>'],
    ['O desafio: conectar descoberta, produtos e atendimento', '<p>O ponto de partida descrito pelo responsável era uma presença digital fragmentada. O desafio foi organizar uma estrutura que apresentasse os produtos, respondesse às necessidades de quem busca presentes em Canaã dos Carajás e facilitasse o contato pelo WhatsApp.</p><p>A estratégia reuniu o site, as páginas dedicadas a produtos e ocasiões e as informações do Perfil da Empresa no Google. O objetivo comercial era conduzir o público interessado até o atendimento com mais clareza sobre a oferta.</p>'],
    ['Site e conteúdo orientados às necessidades do cliente', '<figure class="zd-case-product"><img src="../../assets/images/zadoni-presentes-cesta.webp" width="720" height="720" loading="lazy" decoding="async" alt="Cesta de presentes com itens de café da manhã e laço dourado"><figcaption>Foto de produto apresentada no site da Zadoni Presentes. Exemplo do material visual que acompanha a oferta da loja.</figcaption></figure><p>O trabalho relatado incluiu a criação e otimização do site e a organização de páginas para categorias, produtos e intenções de busca locais. Entre os temas trabalhados estão presentes, buquês, cestas, floricultura, café da manhã e presentes românticos.</p><ul><li>Páginas dedicadas a diferentes produtos e necessidades de compra.</li><li>Conteúdo voltado às dúvidas e buscas do público local.</li><li>Links internos para conectar informações relacionadas.</li><li>Ajustes na experiência em dispositivos móveis.</li><li>Caminhos de contato com o atendimento pelo WhatsApp.</li></ul><p>A proposta foi dar a cada página uma função: explicar uma oferta, responder uma dúvida ou ajudar o visitante a avançar para a conversa.</p>'],
    ['SEO técnico e acompanhamento da indexação', '<p>Adonias descreve a revisão de títulos, descrições, headings, URLs, imagens, links internos e dados estruturados. O escopo também envolveu a configuração do Google Search Console e o acompanhamento da indexação das páginas.</p><p>O site foi conectado ao WhatsApp e aos demais canais digitais do negócio. Essas intervenções fazem parte da base técnica e de conteúdo descrita no projeto; não estabelecem, por si só, uma quantidade de visitas, contatos ou vendas.</p>'],
    ['Perfil da Empresa no Google', '<p>O relato inclui a otimização do Perfil da Empresa no Google, também conhecido como Google Meu Negócio ou GBP. O trabalho abrangeu categorias, produtos, publicações, imagens e informações comerciais.</p><p>Também foram relatadas a correção de inconsistências e a remoção de uma presença duplicada no Google. A apresentação desse trabalho registra a intervenção informada pelo responsável, sem atribuir a ela um efeito isolado sobre a classificação local.</p>'],
    ['O que o projeto passou a reunir', '<p>Segundo o responsável, a Zadoni Presentes passou a contar com uma presença digital mais organizada, com páginas próprias para diferentes produtos e ocasiões e caminhos de contato pelo WhatsApp. Essa é a evolução estrutural descrita no case.</p><p>A estratégia conecta criação de sites, SEO Local, conteúdo, Perfil da Empresa e experiência de navegação. O conjunto foi pensado para apoiar a descoberta e o atendimento, com uma base que possa continuar sendo aprimorada.</p><p><strong>Sobre os resultados:</strong> ainda não são apresentados dados de antes e depois, períodos ou relatórios de tráfego, cobertura de indexação, conversas e vendas. Por isso, esta versão não quantifica crescimento nem atribui aumento comercial às intervenções. Esses indicadores poderão complementar o case quando houver registros comparáveis.</p>'],
    ['Aplicação em outros negócios locais', '<p>O projeto mostra, pelo escopo relatado, como organizar páginas, informações comerciais e atendimento em uma estratégia integrada. O aprendizado central é definir a função de cada canal e de cada página antes de executar melhorias.</p><p>Outros pequenos negócios precisam de uma avaliação própria: oferta, região atendida, estrutura existente e capacidade de responder aos contatos mudam as prioridades. O diagnóstico inicial ajuda a organizar essa conversa, sem assumir que os resultados de um projeto se repetirão em outro.</p>']
  ],
  faq: [
    ['A Zadoni Presentes é um cliente externo?', 'É um negócio próprio de Adonias Joshua, também responsável pela Zadoni Digital. Essa relação está explicitada na apresentação do projeto.'],
    ['Já há métricas de crescimento publicadas neste case?', 'Esta versão reúne o relato das intervenções e da organização da presença digital. A documentação de resultados com períodos e dados comparáveis ainda está em preparação.']
  ],
  sources: [], related: ['seo', 'google']
}, {
  id: 'case-zadoni-digital', kind: 'article', caseStudy: true,
  slug: 'cases/zadoni-digital/', label: 'Case Zadoni Digital',
  image: 'assets/images/tempo10x-interface.jpg',
  imageAlt: 'Tempo 10X no modo aplicativo, com formulário de nova atividade vazio',
  imageCaption: 'Tempo 10X: tela de cadastro de atividade, sem dados pessoais',
  projectUrl: 'https://zadonidigital.com.br/ferramentas/gestao-do-tempo/',
  projectLinkLabel: 'Abrir o Tempo 10X',
  title: 'Case Zadoni Digital: portal, ferramentas e SEO | Zadoni Digital',
  description: 'Conheça o portal criado por Adonias Joshua: conteúdo especializado, Tempo 10X, Matriz de Eisenhower e uma estrutura que conecta desenvolvimento web e SEO.',
  h1: 'Zadoni Digital: conteúdo, ferramentas web e SEO no mesmo projeto',
  lead: 'Um portal próprio desenvolvido por Adonias Joshua para conectar conteúdo especializado, ferramentas de produtividade e uma experiência de navegação orientada ao uso.',
  sections: [
    ['Um projeto próprio de conteúdo e tecnologia', '<p>A Zadoni Digital foi desenvolvida por Adonias Joshua como uma plataforma de conteúdo e ferramentas web. O portal reúne temas de produtividade, mineração, 5S, meio ambiente e gestão de resíduos.</p><p>Este é um case do próprio projeto que apresenta os serviços da Zadoni Digital. O conteúdo e as ferramentas podem ser explorados pelos links desta página, permitindo conhecer as soluções descritas.</p><p><strong>Case em desenvolvimento:</strong> a estrutura e as entregas estão apresentadas; a documentação comparativa de desempenho orgânico será complementada conforme os registros disponíveis.</p>'],
    ['Tempo 10X: acompanhar tempo e atividades', '<p>O Tempo 10X foi criado para apoiar a gestão do tempo e das atividades. A ferramenta reúne controle de sessões, registro de atividades e relatórios para ajudar a observar como o tempo é utilizado.</p><p>O projeto também conta com recursos de organização e persistência local. A ferramenta transforma o tema de gestão do tempo em uma experiência que o visitante pode usar, além de ler sobre o assunto.</p><p><a href="../../ferramentas/gestao-do-tempo/">Conhecer o Tempo 10X →</a></p>'],
    ['Matriz de Eisenhower Online: organizar prioridades', '<figure class="zd-case-preview"><img src="../../assets/images/matriz-eisenhower-interface.jpg" width="1360" height="840" loading="lazy" decoding="async" alt="Matriz de Eisenhower: fazer agora, planejar, delegar e eliminar, sem tarefas cadastradas"><figcaption>Interface da Matriz de Eisenhower em modo aplicativo, sem dados pessoais. Captura em 22 de setembro de 2026.</figcaption></figure><p>A Matriz de Eisenhower Online oferece um espaço para organizar tarefas por urgência e importância. A proposta é apoiar a escolha de prioridades e a organização do trabalho.</p><p>A ferramenta tem uma função diferente do guia educativo: o conteúdo explica o método, enquanto a aplicação permite trabalhar com tarefas. Essa separação orienta a navegação e a intenção de cada página.</p><ul><li><a href="../../ferramentas/matriz-eisenhower/">Usar a Matriz de Eisenhower Online</a></li><li><a href="../../produtividade/matriz-eisenhower/">Ler o guia sobre a Matriz de Eisenhower</a></li></ul>'],
    ['Arquitetura de conteúdo e SEO técnico', '<p>Os conteúdos são organizados por temas, com páginas que apresentam cada área e links para aprofundar assuntos relacionados. A estrutura conecta produtividade, mineração, 5S e gestão ambiental sem transformar todas as páginas em uma única oferta comercial.</p><p>O trabalho técnico inclui títulos e descrições próprios, hierarquia de headings, URLs, canonicals, sitemap, dados estruturados e links internos. A preservação de páginas existentes faz parte da evolução do portal.</p><ul><li><a href="../../portal/">Explorar o portal educacional</a></li><li><a href="../../mineracao/">Conteúdos de mineração</a></li><li><a href="../../5s/">Guias de 5S</a></li><li><a href="../../gestao-ambiental/gestao-de-residuos/">Guia de gestão de resíduos</a></li></ul>'],
    ['Experiência de uso e desenvolvimento web', '<p>O portal combina leitura e aplicação prática. A navegação entre guias e ferramentas, a adaptação a dispositivos móveis e os controles de interação fazem parte dessa experiência.</p><p>As soluções usam HTML, CSS e JavaScript. O projeto possui verificações de SEO e testes para comportamentos das ferramentas, incluindo tarefas, sessões e armazenamento. Esses cuidados ajudam a revisar alterações preservando o trabalho já construído.</p>'],
    ['Acompanhamento pelo Google Search Console', '<p>Segundo Adonias Joshua, o acompanhamento pelo Google Search Console indicou ampliação de impressões, consultas e cliques orgânicos. O histórico do projeto também registra sinais de busca utilizados para orientar revisões de conteúdo.</p><p>Essa evolução é apresentada como relato do responsável. Esta versão do case não reúne exportações com períodos equivalentes, filtros e comparação de antes e depois; portanto, não quantifica o crescimento nem atribui os ganhos a uma ação isolada.</p><p>A proposta de trabalho integra desenvolvimento web, SEO orientado por dados, experiência do usuário e conteúdo especializado. As entregas do portal ilustram essa combinação, enquanto os resultados orgânicos exigem acompanhamento contínuo e leitura contextual dos dados.</p>']
  ],
  faq: [
    ['Este case é de um cliente externo?', 'É o projeto próprio de Adonias Joshua. Essa relação é explicitada para que o visitante possa avaliar o contexto das entregas.'],
    ['Onde posso conhecer as ferramentas?', 'Os links para o Tempo 10X e a Matriz de Eisenhower Online estão nesta página, junto ao portal e aos conteúdos relacionados.'],
    ['O crescimento orgânico já está quantificado?', 'O crescimento foi relatado pelo responsável, mas esta página ainda não apresenta uma comparação de métricas com períodos e filtros definidos.']
  ],
  sources: [], related: ['seo', 'mentoria']
}];
