import assert from 'node:assert/strict';
import { saveTask, classify, validateTask } from '../assets/js/eisenhower10x/tasks.js';
import { reward, progress } from '../assets/js/eisenhower10x/gamification.js';
import { Store, KEYS, emptyState, validateState } from '../assets/js/eisenhower10x/storage.js';
import { summary } from '../assets/js/eisenhower10x/charts.js';
import { formatDateBR, parseDateBR } from '../assets/js/eisenhower10x/dates.js';
assert.equal(formatDateBR('2026-09-13'), '13/09/2026');
assert.equal(parseDateBR('13/09/2026'), '2026-09-13');
assert.equal(parseDateBR('13092026'), '2026-09-13');
assert.equal(parseDateBR(''), '');
assert.equal(parseDateBR('29/02/2028'), '2028-02-29');
for (const date of ['31/02/2026', '29/02/2026', '09/13/2026', '2026-09-13', '01/01/0000']) assert.throws(() => parseDateBR(date), /dd\/mm\/aaaa/);
const map = new Map([['tempo10x.tasks', 'preservado']]);
const storage = { getItem: key => map.get(key) ?? null, setItem: (key, value) => map.set(key, value), removeItem: key => map.delete(key) };
let state = emptyState();
const input = { title: 'Preparar treinamento', description: 'Revisar materiais', category: 'Trabalho', dueDate: '2026-09-30', quadrant: 'plan', status: 'pending' };
const create = (id, day, status = 'pending', quadrant = 'plan') => {
  const result = saveTask(state.tasks, { ...input, status, quadrant }, `${day}T12:00:00.000Z`, id);
  state = { ...state, tasks: result.tasks, gamification: reward(state.gamification, result.task, day) }; return result.task;
};
const first = create('first', '2026-09-10');
assert.equal(progress(state.gamification).xp, 1);
let result = saveTask(state.tasks, { ...first, status: 'completed' }, '2026-09-10T14:00:00.000Z');
state.tasks = result.tasks; state.gamification = reward(state.gamification, result.task, '2026-09-10');
assert.equal(progress(state.gamification, '2026-09-10').xp, 7);
for (const status of ['pending', 'completed', 'pending', 'completed']) {
  result = saveTask(state.tasks, { ...state.tasks[0], status, quadrant: 'do' }); state.tasks = result.tasks; state.gamification = reward(state.gamification, result.task, '2026-09-11');
}
assert.equal(progress(state.gamification, '2026-09-11').xp, 7, 'reabertura/movimento não duplicam XP');
assert.equal(progress(state.gamification, '2026-09-11').today, 0);
create('second', '2026-09-11', 'completed'); create('third', '2026-09-12', 'completed', 'do');
assert.equal(progress(state.gamification, '2026-09-12').streak, 3);
assert.equal(progress(state.gamification, '2026-09-13').streak, 3, 'tolerância durante dia seguinte');
assert.equal(progress(state.gamification, '2026-09-14').streak, 0, 'quebra da sequência');
assert.ok(progress(state.gamification, '2026-09-14').achievements.find(([title]) => title === '3 dias de sequência')[1], 'conquista preservada após quebra');
for (let i = 0; i < 40; i++) create(`task-${i}`, '2026-09-12', 'completed');
assert.equal(progress(state.gamification, '2026-09-12').level, 'Mestre das Prioridades');
assert.equal(progress(state.gamification, '2026-09-12').percent, 100);
for (const [xp, level] of [[0, 'Iniciante'], [29, 'Iniciante'], [30, 'Organizador'], [99, 'Organizador'], [100, 'Estrategista'], [249, 'Estrategista'], [250, 'Mestre das Prioridades']]) assert.equal(progress({ created: Array.from({ length: xp }, (_, i) => `id-${i}`), completed: [] }).level, level);
assert.equal(progress({ created: ['a', 'b', 'c'], completed: [{ id: 'a', xp: 5, day: '2025-12-31' }, { id: 'b', xp: 5, day: '2026-01-01' }, { id: 'c', xp: 5, day: '2026-01-02' }] }, '2026-01-02').streak, 3, 'sequência cruza mês e ano');
assert.equal(summary(state.tasks).completed, 43);
assert.equal(summary(state.tasks).counts.plan, 41);
assert.match(summary([{ quadrant: 'do', status: 'pending' }]).insight, /metade/);
assert.deepEqual([classify(true, true), classify(true, false), classify(false, true), classify(false, false)], ['do', 'plan', 'delegate', 'eliminate']);
assert.throws(() => validateTask({ ...first, dueDate: '2026-02-30' }), /Data/);
assert.throws(() => validateTask({ ...first, title: ' ' }), /Texto/);
assert.throws(() => validateTask({ ...first, quadrant: '__proto__' }), /classificação/);
assert.throws(() => validateState({ ...state, schemaVersion: 99 }), /Versão/);
assert.throws(() => validateState({ ...state, tasks: [first, first] }), /duplicados/);
assert.throws(() => validateState({ ...state, settings: { dailyGoal: 0 } }), /Meta/);
assert.throws(() => validateState({ ...state, gamification: { created: [], completed: [] } }), /inconsistentes/);
assert.throws(() => validateState({ ...state, gamification: { created: ['x'], completed: [{ id: 'x', day: '2026-09-12', xp: 999 }] } }), /conclusões/);
const store = new Store(storage); store.save(state); assert.deepEqual(new Store(storage).load(), state, 'refresh/persistência');
const backup = JSON.parse(JSON.stringify(state)); assert.deepEqual(validateState(backup), state, 'backup/restore');
const xp = progress(state.gamification).xp; state.tasks = []; store.save(state); assert.equal(progress(store.load().gamification).xp, xp, 'exclusão preserva XP');
const original = [...map]; const brokenStorage = { ...storage, setItem: () => { throw new Error('quota'); } };
const quota = new Store(brokenStorage); quota.save(emptyState()); assert.equal(quota.sessionOnly, true); assert.deepEqual([...map], original);
map.set(KEYS[0], '{invalid'); const corrupt = new Store(storage); assert.equal(corrupt.load().tasks.length, 0); corrupt.save(emptyState()); assert.equal(map.get(KEYS[0]), '{invalid');
store.save(state); map.set(KEYS[3], '99'); const future = new Store(storage); future.load(); future.save(emptyState()); assert.equal(map.get(KEYS[3]), '99');
const unavailable = new Store(undefined); unavailable.load(); unavailable.save(emptyState()); assert.equal(unavailable.sessionOnly, true);
store.clear(); assert.equal(map.get('tempo10x.tasks'), 'preservado'); assert.ok(KEYS.every(key => !map.has(key)));
console.log('EISENHOWER: regras de tarefas, validação, backup, quota, corrupção, versão futura, isolamento, XP, níveis e sequência aprovados.');
